name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - build-lib
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  pc-emul:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: clean
        run: make clean
      - name: setup
        run: make setup
      - name: pc-emul test
        run: make -C ../iob_soc_V* pc-emul-test

  verilator:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ !cancelled() }}
    # run after indicated job
    needs: [ pc-emul ]
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # Init mem
      - name: clean
        run: make clean
      - name: setup init_mem
        run: make setup SETUP_ARGS="INIT_MEM=1"
      - name: verilator test
        run: nix-shell -p verilator --run 'make -C ../iob_soc_V* sim-test SIMULATOR=verilator'
      # No init mem
      - name: clean
        run: make clean
      - name: setup
        run: make setup SETUP_ARGS="INIT_MEM=0"
      - name: verilator test
        run: nix-shell -p verilator --run 'make -C ../iob_soc_V* sim-test SIMULATOR=verilator'
      # Init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup init_mem ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=1 RUN_EXTMEM=1"
      - name: verilator test
        run: nix-shell -p verilator --run 'make -C ../iob_soc_V* sim-test SIMULATOR=verilator'
      # No init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=0 RUN_EXTMEM=1"
      - name: verilator test
        run: nix-shell -p verilator --run 'make -C ../iob_soc_V* sim-test SIMULATOR=verilator'
  
  icarus:
    runs-on: self-hosted
    timeout-minutes: 90
    if: ${{ !cancelled() }}
    needs: [ pc-emul ]
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # Init mem
      - name: clean
        run: make clean
      - name: setup init_mem
        run: make setup SETUP_ARGS="INIT_MEM=1"
      - name: icarus test
        run: make -C ../iob_soc_V* sim-test SIMULATOR=icarus
      # No init mem
      - name: clean
        run: make clean
      - name: setup
        run: make setup SETUP_ARGS="INIT_MEM=0"
      - name: icarus test
        run: make -C ../iob_soc_V* sim-test SIMULATOR=icarus
      # Init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup init_mem ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=1 RUN_EXTMEM=1"
      - name: icarus test
        run: make -C ../iob_soc_V* sim-test SIMULATOR=icarus
      # No init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=0 RUN_EXTMEM=1"
      - name: icarus test
        run: make -C ../iob_soc_V* sim-test SIMULATOR=icarus
  
  cyclonev:
    runs-on: self-hosted
    timeout-minutes: 60
    if: ${{ !cancelled() }}
    needs: [ icarus, verilator ]
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # Init mem
      - name: clean
        run: make clean
      - name: setup init_mem
        run: make setup SETUP_ARGS="INIT_MEM=1"
      - name: cyclonev test
        run: make -C ../iob_soc_V* fpga-test BOARD=CYCLONEV-GT-DK
      # No init mem
      - name: clean
        run: make clean
      - name: setup
        run: make setup SETUP_ARGS="INIT_MEM=0"
      - name: cyclonev test
        run: make -C ../iob_soc_V* fpga-test BOARD=CYCLONEV-GT-DK
      # Init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup init_mem ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=1 RUN_EXTMEM=1"
      - name: cyclonev test
        run: make -C ../iob_soc_V* fpga-test BOARD=CYCLONEV-GT-DK
      # No init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=0 RUN_EXTMEM=1"
      - name: cyclonev test
        run: make -C ../iob_soc_V* fpga-test BOARD=CYCLONEV-GT-DK
  
  aes-ku040:
    runs-on: self-hosted
    timeout-minutes: 90
    if: ${{ !cancelled() }}
    needs: [ icarus, verilator ]
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # Init mem
      - name: clean
        run: make clean
      - name: setup init_mem
        run: make setup SETUP_ARGS="INIT_MEM=1"
      - name: ku040 test
        run: make -C ../iob_soc_V* fpga-test BOARD=AES-KU040-DB-G
      # No init mem
      - name: clean
        run: make clean
      - name: setup
        run: make setup SETUP_ARGS="INIT_MEM=0"
      - name: ku040 test
        run: make -C ../iob_soc_V* fpga-test BOARD=AES-KU040-DB-G
      # Init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup init_mem ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=1 RUN_EXTMEM=1"
      - name: ku040 test
        run: make -C ../iob_soc_V* fpga-test BOARD=AES-KU040-DB-G
      # No init mem and Ext mem
      - name: clean
        run: make clean
      - name: setup ext_mem
        run: make setup SETUP_ARGS="INIT_MEM=0 RUN_EXTMEM=1"
      - name: ku040 test
        run: make -C ../iob_soc_V* fpga-test BOARD=AES-KU040-DB-G
  
  # doc:
  #   runs-on: self-hosted
  #   timeout-minutes: 60
  #   if: ${{ !cancelled() }}
  #   needs: [ cyclonev, aes-ku040 ]
  #
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: 'recursive'
  #     - name: test-clean
  #       run: make test-clean
  #     - name: test-doc
  #       run: make test-doc
